### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Mazaalto** [a-bzzzz/ot-harjoitustyo#1]
8.12.2020 klo 12.15
# Koodikatselmointi
## intro
Pahoittelut että palautteenantamisessa kesti, halusin perehtyä projektiisi tarpeeksi hyvin. Hauska idea ja yhdistettynä johonkin ruokakaappi dbeehen niin voisin jopa käyttää! Hienoa
### testit
Kävin läpi testisi sekä jacocosta että oma tekemäsi. Kaikki meni läpi omista testeistäsi hyvin, mutta jacoco herjasi seuraavista asioista:

Severity | Category | Rule | Message | Line
-- | -- | -- | -- | --
Error | sizes | MethodLength | Method length is 35 lines (max allowed is 20). | 52
Error | sizes | MethodLength | Method length is 33 lines (max allowed is 20). | 100
Error | sizes | MethodLength | Method length is 32 lines (max allowed is 20).
Minulla oli täsmälleen sama ongelma omassa koodissani (eli että metodit ovat liian pitkiä). Voisitko keksiä tavan jakaa metodeitasi pienempiin osakokonaisuuksiin? Esimerkiksi create recipe metodissa checkstyle valittaa pituudesta. Yksi vaihtoehto on toteuttaa virheen käsittely jossain muualla tai sitten jakaa reseptin teko eri vaiheisiin, ja koota ne yhdessä metodissa yhteen.
## ratkaisuehdotus
Voi olla että olet jo koodaamassa tätä, mutta yritän silti auttaa. Eli jos tehdessä metodia createRecipeDB() tekisitkin erikseen vaikka metodi 1)  * Recipes: id, name, portions, category, idx_recipe_id
61               */
62              st.execute("CREATE TABLE Recipes(id INTEGER PRIMARY KEY NOT NULL UNIQUE, "
63                      + "name TEXT NOT NULL, "
public class Validation {

    private UsersInterface udbase;
    private Info<User, String> userInfo;

    /**
     * Constructor, creates a Validation object.
     * @param udbase interface of the user databases
     * @see recipes.db.UsersInterface
     */
    public Validation(UsersInterface udbase) {
        this.udbase = udbase;
    }

64                      + "portions INTEGER, "
65                      + "category TEXT)");
66              st.execute("CREATE INDEX idx_recipe_id ON Recipes (id)");
67              /** ja sitten metodi 2 * Stuff: id, stuff_name, amount
69               */
70              st.execute("CREATE TABLE Stuff(id INTEGER NOT NULL,"
71                      + "stuff_name TEXT, "
72                      + "amount TEXT)");
73              /**
74               * Guidance: id, row, text
75               */
76              st.execute("CREATE TABLE Guidance(id INTEGER NOT NULL,"
77                      + "row INTEGER NOT NULL, "
78                      + "text TEXT)");
79              st.execute("COMMIT");
80              db.close();
81              System.out.println("Database " + this.dbase + ".db has been created."); ja sitten vielä metodin jossa kutsutaan edellistä kahta metodia (ja ehkä mahtuu käsittelemään virheetkin.
## koodista
Todella hyvän näköistä koodia, olet jo pitkällä javadocin kanssa, koodissa ei juuri toisteisuutta. Muuttujat nimetty hyvin. Olet suorittanut hyvin olio-ohjelmoinnin perusteita --> luokat fiksuja ja toimivat yhdessä. 
Vielä osa jutuista on toteuttamatta ja ehdottaisin miettimään miten saisit alkunäkemän kivaksi, voisiko siinä olla vaikka listana lisätyt reseptit. Nyt vielä en onnistunut lisäämään reseptiäni, mutta voi olla että korjaat sen jo. Olit kirjoitanut että käyttäisikö categoria luokkaa vai ei.
Minusta ei kannata käyttää ennen kuin reseptejä olisi niin paljon että niiden lajittelu olisi merkityksellistä. Alkuun riittäisi jakaa ne vaikka kuukausiin milloin lisätty. Mutta tämä on tietenkin makuasia. 

Tsemppiä paljon loppurutistukseen, tästä tulee hieno projekti mitä kelpaa näyttää.

**Comment by a-bzzzz** [comment]
Moi Mazaalto, kiitos tuhannesti tarkasta paneutumisesta projektiini ja mahtavasta palautteestasi! Ehdin nyt vain lukaisemaan läpi, mutta huomaan, että jokainen antamasi kehitysidea ja neuvo on tosi arvokas apu. Katson tulevalla viikolla tarkemmin läpi ja otan neuvojasi käytäntöön. Juu, alunperin oli ajatus lisätä tähän mukaan ruokavaraston seuranta - mutta ei nyt onnistu tällä aikataululla.. Siitä vaan käyttöön ja jatkokehittelyyn, jos intoa ja aikaa riittää :+1: Ja kiitos paljon - tsemppiä omaan projektiisikin!

**Comment by a-bzzzz** [comment]
Ja kiitos vielä, että ilmoitit virheestä! Käyttöliittymän init()-metodissa oli reseptitietokannalle jäänyt sama nimi kuin käyttäjätietokannalle. Nyt pitäisi haku ja lisääminen toimia..? Paitsi virheellisillä syötteillä ei kaikkea ole vielä otettu kiinni.
